/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import java.io.BufferedReader;
import java.io.FileReader;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author soporte.sistemas
 */
public class Principal extends javax.swing.JFrame {
    public String Ruta ="C:\\ClienteAGS\\ProgExternos\\ConfigCedulasFirmas.txt";
    public static String RutaCedulas ="";
    public static String RutaFirmas ="";
    
    public Principal() {
        initComponents();
        this.setOpacity(0.9f);
        jButtonCedulas.setOpaque(true);
        
        try{
        //FileReader se usa para Leer el archivo txt que se encuentra
            //en la carpeta local de ADempiere/ProgExternos
            FileReader f = new FileReader(Ruta);
            BufferedReader b = new BufferedReader(f);
            RutaCedulas = b.readLine();
            RutaFirmas = b.readLine();
            b.close();
            } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCedulas = new javax.swing.JButton();
        jButtonFirmas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jlbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Capturador de Cedulas y Firmas");
        setName("JFramePrincipal"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jButtonCedulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cedulas.png"))); // NOI18N
        jButtonCedulas.setToolTipText("Cedulas");
        jButtonCedulas.setBorderPainted(false);
        jButtonCedulas.setContentAreaFilled(false);
        jButtonCedulas.setFocusPainted(false);
        jButtonCedulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCedulasMouseClicked(evt);
            }
        });
        jButtonCedulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCedulasActionPerformed(evt);
            }
        });

        jButtonFirmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/firmas.png"))); // NOI18N
        jButtonFirmas.setToolTipText("Firmas");
        jButtonFirmas.setBorderPainted(false);
        jButtonFirmas.setContentAreaFilled(false);
        jButtonFirmas.setFocusPainted(false);
        jButtonFirmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFirmasMouseClicked(evt);
            }
        });
        jButtonFirmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirmasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Gerencia TI  (2021) -  PREVALER, C.A.");

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Unavailable_24px.png"))); // NOI18N
        jButton9.setToolTipText("Cerrar");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Unavailable_22px.png"))); // NOI18N
        jButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Unavailable_22px.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jlbTitulo.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jlbTitulo.setText("Capturador de Cedulas y Firmas        (Ver. 2.0)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonFirmas, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCedulas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFirmas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     
    private void jButtonCedulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCedulasMouseClicked
        //Boton Cedulas
        Camara vc = new Camara ();
        vc.setVisible(true);
        vc.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_jButtonCedulasMouseClicked

    private void jButtonCedulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCedulasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButtonCedulasActionPerformed

    private void jButtonFirmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFirmasMouseClicked
        // TODO add your handling code here:
         //Boton Cedulas
        Firma1 vf = new Firma1 ();
        vf.setVisible(true);
        vf.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonFirmasMouseClicked

    private void jButtonFirmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFirmasActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        System.exit(0);  
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCedulas;
    private javax.swing.JButton jButtonFirmas;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlbTitulo;
    // End of variables declaration//GEN-END:variables
}
